import { Area, AreaChart, Bar, BarChart, CartesianGrid, ResponsiveContainer, Tooltip as ChartTooltip, XAxis, YAxis } from "recharts";
import { ArrowDown, ArrowUp, BellRing, ChevronDown, ChevronUp, Expand, GripVertical, LineChart, Minus, MoreHorizontal, Plus, Search, SlidersHorizontal, Trash2, TrendingDown, TrendingUp } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";
import { companies, getAnalysis, getCompany, getEarnings, getNews, makeChartData, marketSymbols } from "./data";
import { useDashboard } from "./dashboard-context";
import { Change, Panel, SampleBadge, Term } from "./ui";

export function MarketOverviewStrip() {
  const { preferences } = useDashboard();
  if (!preferences.visiblePanels.overview) return null;
  return <section aria-label="Market overview" className="grid border-y border-border bg-card sm:grid-cols-5">{marketSymbols.map((symbol, index) => { const item = getCompany(symbol); return <div key={symbol} className={cn("flex min-h-16 items-center justify-between gap-3 px-4 py-2", index > 0 && "border-t border-border sm:border-l sm:border-t-0")}><div><div className="flex items-center gap-2"><b className="text-xs">{item.symbol}</b><SampleBadge /></div><p className="mt-1 font-mono text-xs tabular-nums">{item.price.toFixed(2)}</p></div><Change value={item.change} /></div>; })}</section>;
}

export function WatchlistPanel({ management = false }: { management?: boolean }) {
  const { watchlist, selectedSymbol, setSelectedSymbol, addTicker, removeTicker, moveTicker } = useDashboard();
  const [query, setQuery] = useState("");
  const matches = companies.filter((item) => !watchlist.includes(item.symbol) && `${item.symbol} ${item.name}`.toLowerCase().includes(query.toLowerCase())).slice(0, 5);
  return <Panel title={management ? "Watchlist management" : "My Watchlist"} eyebrow={`${watchlist.length} of 15 symbols`} className={cn(!management && "h-full")} action={<SampleBadge />}>
    <div className="border-b border-border p-3"><div className="relative"><Search className="absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Add symbol or company" className="h-8 bg-secondary/40 pl-8 pr-8 text-xs" /><Plus className="absolute right-2.5 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /></div>{query && matches.length > 0 && <div className="mt-2 border border-border bg-popover p-1">{matches.map((item) => <button type="button" key={item.symbol} onClick={() => { addTicker(item.symbol); setQuery(""); }} className="flex w-full items-center justify-between px-2 py-2 text-left text-xs hover:bg-accent"><span><b>{item.symbol}</b> <span className="ml-2 text-muted-foreground">{item.name}</span></span><Plus className="size-3" /></button>)}</div>}</div>
    <div className={cn("overflow-y-auto", management ? "max-h-[580px]" : "max-h-[560px]")}>{watchlist.map((symbol, index) => { const item = getCompany(symbol); const selected = selectedSymbol === symbol; return <div key={symbol} role="button" tabIndex={0} onClick={() => setSelectedSymbol(symbol)} onKeyDown={(event) => { if (event.key === "Enter") setSelectedSymbol(symbol); }} className={cn("group grid min-h-[59px] cursor-pointer grid-cols-[1fr_auto] items-center gap-2 border-b border-border px-3 py-2 outline-none transition-colors focus-visible:ring-1 focus-visible:ring-ring", selected ? "border-l-2 border-l-primary bg-primary/8" : "border-l-2 border-l-transparent hover:bg-accent/60")}>
      <div className="min-w-0"><div className="flex items-center gap-2"><b className="text-xs">{symbol}</b>{item.earningsDays && item.earningsDays <= 18 && <span className="rounded-sm bg-warning/10 px-1 py-0.5 text-[8px] font-bold text-warning">E {item.earningsDays}D</span>}</div><p className="mt-1 truncate text-[10px] text-muted-foreground">{item.name}</p></div>
      <div className="flex items-center gap-2"><div className="text-right"><p className="font-mono text-xs tabular-nums">${item.price.toFixed(2)}</p><Change value={item.change} /></div>{management ? <div className="flex"><Button variant="ghost" size="icon" className="size-6" disabled={index === 0} onClick={(e) => { e.stopPropagation(); moveTicker(symbol, -1); }} aria-label={`Move ${symbol} up`}><ChevronUp className="size-3" /></Button><Button variant="ghost" size="icon" className="size-6" disabled={index === watchlist.length - 1} onClick={(e) => { e.stopPropagation(); moveTicker(symbol, 1); }} aria-label={`Move ${symbol} down`}><ChevronDown className="size-3" /></Button><Button variant="ghost" size="icon" className="size-6 text-negative" onClick={(e) => { e.stopPropagation(); removeTicker(symbol); }} aria-label={`Remove ${symbol}`}><Trash2 className="size-3" /></Button></div> : item.change >= 0 ? <TrendingUp className="size-3.5 text-positive" /> : <TrendingDown className="size-3.5 text-negative" />}</div>
    </div>; })}</div>
  </Panel>;
}

export function TradingViewChartPanel() {
  const { selectedSymbol, preferences, updatePreferences } = useDashboard();
  const company = getCompany(selectedSymbol);
  const data = makeChartData(selectedSymbol);
  const [chartType, setChartType] = useState("Area");
  const [expanded, setExpanded] = useState(false);
  const [indicators, setIndicators] = useState(["Volume"]);
  const timeframes = ["1D", "5D", "1M", "3M", "6M", "1Y"];
  return <Panel title={`${company.symbol} · ${company.name}`} eyebrow="Chart workspace · simulated history" className={cn(expanded && "fixed inset-4 z-50 shadow-2xl")} action={<div className="flex items-center gap-1"><SampleBadge /><Button variant="ghost" size="icon" className="size-7" onClick={() => setExpanded(!expanded)} aria-label="Expand chart"><Expand className="size-3.5" /></Button><Button variant="ghost" size="icon" className="size-7" aria-label="Chart options"><MoreHorizontal className="size-3.5" /></Button></div>}>
    <div className="flex flex-wrap items-center gap-3 border-b border-border px-4 py-3"><div><p className="font-mono text-2xl font-semibold tabular-nums">${company.price.toFixed(2)}</p><Change value={company.change} className="text-sm" /></div><div className="ml-auto flex flex-wrap items-center gap-2"><div className="flex border border-border bg-secondary/40">{timeframes.map((time) => <button key={time} type="button" onClick={() => updatePreferences({ timeframe: time })} className={cn("h-7 min-w-8 px-2 text-[10px] font-semibold", preferences.timeframe === time ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:text-foreground")}>{time}</button>)}</div><Select value={chartType} onValueChange={setChartType}><SelectTrigger className="h-7 w-24 text-[10px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Area">Area</SelectItem><SelectItem value="Bars">Bars</SelectItem></SelectContent></Select><Button variant="outline" size="sm" className="h-7 text-[10px]" onClick={() => setIndicators((current) => current.includes("SMA 20") ? current.filter((item) => item !== "SMA 20") : [...current, "SMA 20"])}><SlidersHorizontal className="size-3" />Indicators</Button></div></div>
    <div className="relative h-[330px] p-3"><div className="absolute left-5 top-4 z-10 flex gap-2">{indicators.map((item) => <span key={item} className="border border-border bg-background/85 px-1.5 py-0.5 text-[9px] text-muted-foreground">{item}</span>)}</div><ResponsiveContainer width="100%" height="100%">{chartType === "Area" ? <AreaChart data={data} margin={{ top: 18, right: 8, bottom: 0, left: 0 }}><defs><linearGradient id="priceFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="var(--color-primary)" stopOpacity={0.28}/><stop offset="100%" stopColor="var(--color-primary)" stopOpacity={0}/></linearGradient></defs><CartesianGrid stroke="var(--color-border)" strokeDasharray="2 5" vertical={false}/><XAxis dataKey="time" hide/><YAxis domain={["dataMin - 2", "dataMax + 2"]} orientation="right" tick={{ fill: "var(--color-muted-foreground)", fontSize: 10 }} axisLine={false} tickLine={false} width={48}/><ChartTooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--border)", fontSize: 11 }} formatter={(value) => [`$${value}`, "Simulated price"]}/><Area type="monotone" dataKey="price" stroke="var(--color-primary)" strokeWidth={1.8} fill="url(#priceFill)" isAnimationActive={false} /></AreaChart> : <BarChart data={data}><CartesianGrid stroke="var(--color-border)" strokeDasharray="2 5" vertical={false}/><XAxis dataKey="time" hide/><YAxis orientation="right" tick={{ fill: "var(--color-muted-foreground)", fontSize: 10 }} axisLine={false} tickLine={false}/><ChartTooltip contentStyle={{ background: "var(--popover)", border: "1px solid var(--border)", fontSize: 11 }}/><Bar dataKey="price" fill="var(--color-primary)" isAnimationActive={false} /></BarChart>}</ResponsiveContainer><div className="pointer-events-none absolute bottom-4 left-5 flex items-center gap-2 text-[9px] text-muted-foreground"><LineChart className="size-3" />TradingView adapter ready · no live connection</div></div>
  </Panel>;
}

export function MarketNewsPanel({ full = false }: { full?: boolean }) {
  const { selectedSymbol } = useDashboard(); const [filter, setFilter] = useState("All");
  const items = useMemo(() => getNews(selectedSymbol).filter((item) => filter === "All" || filter === "High Impact" && item.impact === "High" || filter === "Earnings" && item.category === "Earnings" || filter === "Company News" && item.category === "Company News"), [selectedSymbol, filter]);
  return <Panel title="Market Intelligence" eyebrow={`${selectedSymbol} news · sample feed`} action={<SampleBadge>Sample news</SampleBadge>}><Tabs value={filter} onValueChange={setFilter} className="border-b border-border px-3 pt-2"><TabsList className="h-8 w-full justify-start rounded-none bg-transparent p-0">{["All", "High Impact", "Earnings", "Company News"].map((tab) => <TabsTrigger key={tab} value={tab} className="h-8 rounded-none px-2 text-[10px] data-[state=active]:border-b data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:shadow-none">{tab}</TabsTrigger>)}</TabsList></Tabs><div className={cn("divide-y divide-border overflow-y-auto", full ? "max-h-none" : "max-h-[370px]")}>{items.length === 0 ? <p className="p-6 text-center text-xs text-muted-foreground">No sample stories match this filter.</p> : items.map((item) => <article key={item.id} className="p-4 transition-colors hover:bg-accent/35"><div className="flex items-center gap-2 text-[9px] uppercase tracking-wide text-muted-foreground"><span className={cn("size-1.5 rounded-full", item.impact === "High" ? "bg-negative" : item.impact === "Medium" ? "bg-warning" : "bg-muted-foreground")} /><span>{item.impact} impact</span><span>•</span><span>{item.category}</span><span className="ml-auto">{item.timestamp}</span></div><h3 className="mt-2 text-xs font-semibold leading-relaxed">{item.headline}</h3><p className="mt-1.5 text-[11px] leading-relaxed text-muted-foreground">{item.summary}</p><div className="mt-2 flex items-center justify-between text-[9px]"><span className="text-muted-foreground">{item.source}</span><b className="text-primary">{item.symbol}</b></div></article>)}</div></Panel>;
}

export function EarningsMonitorPanel({ full = false }: { full?: boolean }) {
  const { selectedSymbol } = useDashboard(); const earnings = getEarnings(selectedSymbol);
  return <Panel title="Earnings Monitor" eyebrow={`${selectedSymbol} · sample calendar`} action={<SampleBadge />}><div className={cn("grid", full && "lg:grid-cols-2")}><div className="border-b border-border p-4 lg:border-r"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase text-muted-foreground">Next report</p><p className="mt-1 text-lg font-semibold">{earnings.date}</p><p className="mt-1 text-xs text-muted-foreground">{earnings.session}</p></div><div className="border border-warning/30 bg-warning/10 px-3 py-2 text-center"><strong className="block font-mono text-xl text-warning">{earnings.days}</strong><span className="text-[9px] uppercase text-warning">Days</span></div></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="bg-secondary/50 p-3"><p className="text-[9px] uppercase text-muted-foreground">Est. EPS</p><p className="mt-1 font-mono text-sm">{earnings.estimatedEps}</p></div><div className="bg-secondary/50 p-3"><p className="text-[9px] uppercase text-muted-foreground">Reported EPS</p><p className="mt-1 text-sm text-muted-foreground">Pending</p></div></div></div><div className="p-4"><p className="mb-3 text-[10px] font-semibold uppercase text-muted-foreground">Historical next-day reaction</p><div className="space-y-3">{earnings.history.map((item) => <div key={item.quarter} className="grid grid-cols-[3.5rem_1fr_3rem] items-center gap-2"><span className="text-[10px] text-muted-foreground">{item.quarter}</span><div className="h-1 bg-muted"><div className={cn("h-full", item.reaction >= 0 ? "bg-positive" : "bg-negative", Math.abs(item.reaction) >= 6 ? "w-3/4" : Math.abs(item.reaction) >= 4 ? "w-3/5" : Math.abs(item.reaction) >= 2 ? "w-2/5" : "w-1/4")} /></div><span className={cn("text-right font-mono text-[10px]", item.reaction >= 0 ? "text-positive" : "text-negative")}>{item.reaction >= 0 ? "+" : ""}{item.reaction}%</span></div>)}</div></div></div></Panel>;
}

export function AITradeAnalyzerPanel({ full = false }: { full?: boolean }) {
  const { selectedSymbol } = useDashboard(); const analysis = getAnalysis(selectedSymbol);
  const biasStyle = analysis.bias === "Bullish" ? "text-positive bg-positive/10 border-positive/25" : analysis.bias === "Bearish" ? "text-negative bg-negative/10 border-negative/25" : "text-warning bg-warning/10 border-warning/25";
  return <Panel title="AI Trade Setup Analyzer" eyebrow={`${selectedSymbol} · educational sample`} action={<span className={cn("border px-2 py-1 text-[9px] font-bold uppercase", biasStyle)}>{analysis.status}</span>}><div className={cn("grid", full && "xl:grid-cols-[0.8fr_1fr_1fr]")}><div className="border-b border-border p-4 xl:border-b-0 xl:border-r"><p className="text-[10px] uppercase text-muted-foreground">Overall technical bias</p><div className="mt-2 flex items-center gap-3"><span className={cn("flex size-10 items-center justify-center border", biasStyle)}>{analysis.bias === "Bullish" ? <ArrowUp /> : analysis.bias === "Bearish" ? <ArrowDown /> : <Minus />}</span><div><p className={cn("text-xl font-semibold", biasStyle.split(" ")[0])}>{analysis.bias}</p><p className="text-[10px] text-muted-foreground">Confidence {analysis.confidence}% · incomplete data</p></div></div><div className="mt-4 space-y-3 text-[11px]"><Metric label="Trend strength" value={analysis.trend} /><Metric label="Momentum" value={analysis.momentum} /><Metric label="Volume confirmation" value={analysis.volume} /></div></div><div className="border-b border-border p-4 xl:border-b-0 xl:border-r"><div className="grid grid-cols-2 gap-4"><List title="Support" items={analysis.support} term="Support" /><List title="Resistance" items={analysis.resistance} term="Resistance" /></div><List title="Upcoming catalysts" items={analysis.catalysts} className="mt-4" /></div><div className="p-4"><div className="grid gap-4 sm:grid-cols-2"><List title="Potential Call conditions" items={analysis.callConditions} tone="positive" term="Call" /><List title="Potential Put conditions" items={analysis.putConditions} tone="negative" term="Put" /></div><List title="Risk factors" items={analysis.risk} tone="warning" className="mt-4" /></div></div><div className="border-t border-warning/20 bg-warning/5 px-4 py-3 text-[10px] leading-relaxed text-muted-foreground"><strong className="text-warning">Educational use only.</strong> This sample analysis is not live, validated, or a recommendation to trade. Options involve substantial risk and can lose their full value.</div></Panel>;
}

function Metric({ label, value }: { label: string; value: string }) { return <div><div className="mb-1 flex justify-between gap-4"><span className="text-muted-foreground">{label}</span><span className="text-right">{value}</span></div><div className="h-1 bg-muted"><div className="h-full w-2/5 bg-primary" /></div></div>; }
function List({ title, items, tone, term, className }: { title: string; items: string[]; tone?: "positive" | "negative" | "warning"; term?: "Call" | "Put" | "Support" | "Resistance"; className?: string }) { return <div className={className}><p className="mb-2 text-[10px] font-semibold uppercase text-muted-foreground">{term ? <Term>{term}</Term> : title}</p><ul className="space-y-1.5">{items.map((item) => <li key={item} className="flex gap-2 text-[10px] leading-relaxed"><span className={cn("mt-1.5 size-1 shrink-0 rounded-full bg-muted-foreground", tone === "positive" && "bg-positive", tone === "negative" && "bg-negative", tone === "warning" && "bg-warning")} />{item}</li>)}</ul></div>; }

export function Dashboard() {
  const { preferences } = useDashboard();
  return <div><MarketOverviewStrip /><div className="p-3 md:p-4"><div className="mb-3 flex items-end justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">Workspace 01</p><h1 className="mt-1 text-xl font-semibold">Trading Dashboard</h1></div><div className="hidden items-center gap-2 text-[10px] text-muted-foreground sm:flex"><BellRing className="size-3" />Sample intelligence · refreshed for prototype</div></div><div className="grid min-w-0 gap-3 xl:grid-cols-[250px_minmax(0,1fr)_340px]"><div className="xl:row-span-2"><WatchlistPanel /></div><TradingViewChartPanel />{preferences.visiblePanels.news && <div className="xl:row-span-2"><MarketNewsPanel /></div>}{preferences.visiblePanels.earnings && <EarningsMonitorPanel />}{preferences.visiblePanels.analyzer && <div className="xl:col-span-2"><AITradeAnalyzerPanel /></div>}</div></div></div>;
}
