import { BellRing, BrainCircuit, Check, ChevronDown, ChevronUp, Expand, MoreHorizontal, PencilRuler, Plus, Search, SlidersHorizontal, Trash2, TrendingDown, TrendingUp, Webhook } from "lucide-react";
import { useMemo, useState } from "react";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Tabs, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { cn } from "@/lib/utils";
import { useBars } from "./use-bars";
import { companies, getCompany, getEarnings, getNews, marketSymbols } from "./data";
import { useDashboard } from "./dashboard-context";
import { Change, DataState, Panel, SampleBadge, StatusDot, Why } from "./ui";
import { AITradeSetupPanel } from "./trade-setup-panel";
import { OptionsContractLab } from "./options-contract-lab";
import { TradingViewChart } from "./tradingview-chart";

export function MarketOverviewStrip() {
  const { preferences } = useDashboard();
  if (!preferences.visiblePanels.overview) return null;
  return <section aria-label="Market overview" className="grid border-y border-border bg-card sm:grid-cols-5">{marketSymbols.map((symbol, index) => { const item = getCompany(symbol); return <div key={symbol} className={cn("flex min-h-16 items-center justify-between gap-3 px-4 py-2", index > 0 && "border-t border-border sm:border-l sm:border-t-0")}><div><div className="flex items-center gap-2"><b className="text-xs">{item.symbol}</b><SampleBadge /></div><p className="mt-1 font-mono text-xs tabular-nums">{item.price.toFixed(2)}</p></div><Change value={item.change} /></div>; })}</section>;
}

export function MarketRegimeIndicator() {
  return <section aria-label="Market regime" className="flex flex-wrap items-center gap-3 border border-border bg-card px-3 py-2"><div><p className="text-[9px] font-semibold uppercase text-muted-foreground">Market regime</p><div className="mt-0.5 flex items-center gap-2"><span className="size-1.5 rounded-full bg-positive" /><strong className="text-xs text-positive">Risk-On</strong><SampleBadge>Simulated</SampleBadge></div></div><div className="ml-auto max-w-lg text-right text-[9px] leading-relaxed text-muted-foreground">Prototype classification based on sample SPY, QQQ, and VIX conditions. Live broad-market data is not connected.</div></section>;
}

export function WatchlistPanel({ management = false }: { management?: boolean }) {
  const { watchlist, selectedSymbol, setSelectedSymbol, addTicker, removeTicker, moveTicker } = useDashboard();
  const [query, setQuery] = useState("");
  const matches = companies.filter((item) => !watchlist.includes(item.symbol) && `${item.symbol} ${item.name}`.toLowerCase().includes(query.toLowerCase())).slice(0, 5);
  return <Panel title={management ? "Watchlist management" : "My Watchlist"} eyebrow={`${watchlist.length} of 15 symbols`} className={cn(!management && "h-full")} action={<SampleBadge />}>
    <div className="border-b border-border p-3"><div className="relative"><Search className="absolute left-2.5 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /><Input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Add symbol or company" className="h-8 bg-secondary/40 pl-8 pr-8 text-xs" /><Plus className="absolute right-2.5 top-1/2 size-3.5 -translate-y-1/2 text-muted-foreground" /></div>{query && matches.length > 0 && <div className="mt-2 border border-border bg-popover p-1">{matches.map((item) => <button type="button" key={item.symbol} onClick={() => { addTicker(item.symbol); setQuery(""); }} className="flex w-full items-center justify-between px-2 py-2 text-left text-xs hover:bg-accent"><span><b>{item.symbol}</b> <span className="ml-2 text-muted-foreground">{item.name}</span></span><Plus className="size-3" /></button>)}</div>}</div>
    <div className={cn("overflow-y-auto", management ? "max-h-[580px]" : "max-h-[560px]")}>{watchlist.map((symbol, index) => { const item = getCompany(symbol); const selected = selectedSymbol === symbol; return <div key={symbol} role="button" tabIndex={0} onClick={() => setSelectedSymbol(symbol)} onKeyDown={(event) => { if (event.key === "Enter") setSelectedSymbol(symbol); }} className={cn("group grid min-h-[59px] cursor-pointer grid-cols-[1fr_auto] items-center gap-2 border-b border-border px-3 py-2 outline-none transition-colors focus-visible:ring-1 focus-visible:ring-ring", selected ? "border-l-2 border-l-primary bg-primary/8" : "border-l-2 border-l-transparent hover:bg-accent/60")}>
      <div className="min-w-0"><div className="flex items-center gap-2"><b className="text-xs">{symbol}</b>{item.earningsDays && item.earningsDays <= 18 && <span className="rounded-sm bg-warning/10 px-1 py-0.5 text-[8px] font-bold text-warning">E {item.earningsDays}D</span>}</div><p className="mt-1 truncate text-[10px] text-muted-foreground">{item.name}</p></div>
      <div className="flex items-center gap-2"><div className="text-right"><p className="font-mono text-xs tabular-nums">${item.price.toFixed(2)}</p><Change value={item.change} /></div>{management ? <div className="flex"><Button variant="ghost" size="icon" className="size-6" disabled={index === 0} onClick={(e) => { e.stopPropagation(); moveTicker(symbol, -1); }} aria-label={`Move ${symbol} up`}><ChevronUp className="size-3" /></Button><Button variant="ghost" size="icon" className="size-6" disabled={index === watchlist.length - 1} onClick={(e) => { e.stopPropagation(); moveTicker(symbol, 1); }} aria-label={`Move ${symbol} down`}><ChevronDown className="size-3" /></Button><Button variant="ghost" size="icon" className="size-6 text-negative" onClick={(e) => { e.stopPropagation(); removeTicker(symbol); }} aria-label={`Remove ${symbol}`}><Trash2 className="size-3" /></Button></div> : item.change >= 0 ? <TrendingUp className="size-3.5 text-positive" /> : <TrendingDown className="size-3.5 text-negative" />}</div>
    </div>; })}</div>
  </Panel>;
}

export function TradingViewChartPanel() {
  const { selectedSymbol, preferences, updatePreferences } = useDashboard();
  const company = getCompany(selectedSymbol);
  const live = useBars(selectedSymbol);
  const [chartType, setChartType] = useState("Area");
  const [expanded, setExpanded] = useState(false);
  const [indicators, setIndicators] = useState(["Volume"]);
  const [drawingTools, setDrawingTools] = useState(false);
  const timeframes = ["1m", "5m", "15m", "30m", "1H", "4H", "1D", "1W"];
  return <Panel title="CHART WORKSPACE" eyebrow="TradingView · live chart" className={cn(expanded && "fixed inset-3 z-50 shadow-2xl")} action={<div className="flex items-center gap-1"><SampleBadge /><Button variant="ghost" size="icon" className="size-7" aria-label="Chart options"><MoreHorizontal className="size-3.5" /></Button></div>}>
    <div className="flex flex-wrap items-end gap-4 border-b border-border px-4 py-4"><div className="min-w-48"><div className="flex items-center gap-2"><h2 className="text-xl font-bold">{company.symbol}</h2><span className="text-xs text-muted-foreground">{company.name}</span></div><div className="mt-2 flex items-end gap-3">{live.quote ? <><p className="font-mono text-3xl font-semibold tabular-nums">${live.quote.price.toFixed(2)}</p><Change value={live.quote.change} className="mb-1 text-sm" /><span className="mb-1 inline-flex items-center gap-1 text-[9px] font-semibold uppercase tracking-wider text-positive"><StatusDot status="connected" />Real-time (IEX)</span></> : <p className="font-mono text-sm text-muted-foreground">{live.state === "loading" ? "Loading price…" : live.state === "empty" ? "No bars returned" : live.state === "error" ? "Price unavailable (provider error)" : "Live provider not connected"}</p>}</div></div><div className="ml-auto"><Select value={chartType} onValueChange={setChartType}><SelectTrigger className="h-8 w-24 text-[10px]"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="Area">Area</SelectItem><SelectItem value="Bars">Bars</SelectItem></SelectContent></Select></div></div>
    <div className="flex flex-wrap items-center gap-1 border-b border-border bg-secondary/20 px-3 py-2"><div className="flex flex-wrap border border-border bg-background">{timeframes.map((time) => <Button key={time} type="button" variant="ghost" size="sm" onClick={() => updatePreferences({ timeframe: time })} className={cn("h-7 min-w-8 rounded-none px-2 text-[10px]", preferences.timeframe === time && "bg-primary text-primary-foreground hover:bg-primary hover:text-primary-foreground")}>{time}</Button>)}</div><Button variant={indicators.includes("SMA 20") ? "secondary" : "ghost"} size="sm" className="h-7 text-[10px]" onClick={() => setIndicators((current) => current.includes("SMA 20") ? current.filter((item) => item !== "SMA 20") : [...current, "SMA 20"])}><SlidersHorizontal className="size-3" />Indicators</Button><Button variant={drawingTools ? "secondary" : "ghost"} size="sm" className="h-7 text-[10px]" onClick={() => setDrawingTools((value) => !value)}><PencilRuler className="size-3" />Drawing tools</Button><Button variant="ghost" size="sm" className="ml-auto h-7 text-[10px]" onClick={() => setExpanded(!expanded)}><Expand className="size-3" />Fullscreen</Button></div>
    <div className={cn("relative h-[440px] p-3", expanded && "h-[calc(100vh-12rem)]")}><div className="absolute left-5 top-4 z-10 flex gap-2">{indicators.map((item) => <span key={item} className="border border-border bg-background/85 px-1.5 py-0.5 text-[9px] text-muted-foreground">{item}</span>)}{drawingTools && <span className="border border-primary/30 bg-primary/10 px-1.5 py-0.5 text-[9px] text-primary">Drawing mode preview</span>}</div><TradingViewChart symbol={selectedSymbol} interval={preferences.timeframe} /></div>
  </Panel>;
}

export function MarketNewsPanel({ full = false }: { full?: boolean }) {
  const { selectedSymbol } = useDashboard(); const [filter, setFilter] = useState("All");
  const items = useMemo(() => getNews(selectedSymbol).filter((item) => filter === "All" || filter === "High Impact" && item.impact === "High" || filter === "Earnings" && item.category === "Earnings" || filter === "Company News" && item.category === "Company"), [selectedSymbol, filter]);
  return <Panel title="Catalyst Intelligence" eyebrow={`${selectedSymbol} news · sample feed`} action={<SampleBadge>Sample news</SampleBadge>}><Tabs value={filter} onValueChange={setFilter} className="overflow-x-auto border-b border-border px-3 pt-2"><TabsList className="h-8 w-max justify-start rounded-none bg-transparent p-0">{["All", "Earnings", "Company News", "High Impact"].map((tab) => <TabsTrigger key={tab} value={tab} className="h-8 rounded-none px-2 text-[10px] data-[state=active]:border-b data-[state=active]:border-primary data-[state=active]:bg-transparent data-[state=active]:shadow-none">{tab}</TabsTrigger>)}</TabsList></Tabs><div className={cn("divide-y divide-border overflow-y-auto", full ? "max-h-none" : "max-h-[520px]")}>{items.length === 0 ? <p className="p-6 text-center text-xs text-muted-foreground">No sample stories match this filter.</p> : items.map((item) => <article key={item.id} className="p-4 transition-colors hover:bg-accent/35"><div className="flex flex-wrap items-center gap-2 text-[9px] uppercase text-muted-foreground"><span className={cn("size-1.5 rounded-full", item.impact === "High" ? "bg-negative" : item.impact === "Medium" ? "bg-warning" : "bg-muted-foreground")} /><b className={item.impact === "High" ? "text-negative" : item.impact === "Medium" ? "text-warning" : "text-muted-foreground"}>{item.impact}</b><Why title={`Why is this ${item.impact.toLowerCase()} impact?`}>{item.whyItMatters}</Why><span>•</span><span>{item.category}</span><span className="ml-auto">{item.timestamp}</span></div><h3 className="mt-2 text-xs font-semibold leading-relaxed">{item.headline}</h3><p className="mt-1.5 text-[11px] leading-relaxed text-muted-foreground">{item.summary}</p><div className="mt-3 border-l-2 border-primary/50 pl-3"><p className="text-[9px] font-semibold uppercase text-primary">Why it matters</p><p className="mt-1 text-[10px] leading-relaxed text-muted-foreground">{item.whyItMatters}</p></div><div className="mt-2 flex items-center justify-between text-[9px]"><span className="text-muted-foreground">{item.source}</span><b className="text-primary">{item.symbol}</b></div></article>)}</div></Panel>;
}

export function EarningsMonitorPanel({ full = false }: { full?: boolean }) {
  const { selectedSymbol } = useDashboard(); const earnings = getEarnings(selectedSymbol);
  return <Panel title="Earnings Monitor" eyebrow={`${selectedSymbol} · sample calendar`} action={<SampleBadge />}><div className={cn("grid", full && "lg:grid-cols-2")}><div className="border-b border-border p-4 lg:border-r"><div className="flex items-start justify-between"><div><p className="text-[10px] uppercase text-muted-foreground">Next report</p><p className="mt-1 text-lg font-semibold">{earnings.date}</p><p className="mt-1 text-xs text-muted-foreground">{earnings.session}</p></div><div className="border border-warning/30 bg-warning/10 px-3 py-2 text-center"><strong className="block font-mono text-xl text-warning">{earnings.days}</strong><span className="text-[9px] uppercase text-warning">Days</span></div></div><div className="mt-4 grid grid-cols-2 gap-2"><div className="bg-secondary/50 p-3"><p className="text-[9px] uppercase text-muted-foreground">Est. EPS</p><p className="mt-1 font-mono text-sm">{earnings.estimatedEps}</p></div><div className="bg-secondary/50 p-3"><p className="text-[9px] uppercase text-muted-foreground">Reported EPS</p><p className="mt-1 text-sm text-muted-foreground">Pending</p></div></div></div><div className="p-4"><p className="mb-3 text-[10px] font-semibold uppercase text-muted-foreground">Historical next-day reaction</p><div className="space-y-3">{earnings.history.map((item) => <div key={item.quarter} className="grid grid-cols-[3.5rem_1fr_3rem] items-center gap-2"><span className="text-[10px] text-muted-foreground">{item.quarter}</span><div className="h-1 bg-muted"><div className={cn("h-full", item.reaction >= 0 ? "bg-positive" : "bg-negative", Math.abs(item.reaction) >= 6 ? "w-3/4" : Math.abs(item.reaction) >= 4 ? "w-3/5" : Math.abs(item.reaction) >= 2 ? "w-2/5" : "w-1/4")} /></div><span className={cn("text-right font-mono text-[10px]", item.reaction >= 0 ? "text-positive" : "text-negative")}>{item.reaction >= 0 ? "+" : ""}{item.reaction}%</span></div>)}</div></div></div></Panel>;
}

export function AITradeAnalyzerPanel({ full = false }: { full?: boolean }) {
  return <AITradeSetupPanel full={full} />;
}

export function AlertsPanel() {
  const { selectedSymbol } = useDashboard();
  const alerts = [
    { time: "10:42 AM", type: "TradingView Alert", trigger: "Price crossed sample resistance", status: "Triggered", ai: true, tone: "positive" },
    { time: "09:58 AM", type: "Volume Alert", trigger: "Relative volume threshold observed", status: "Review", ai: false, tone: "warning" },
    { time: "Yesterday", type: "Catalyst Alert", trigger: "Sample earnings reminder created", status: "Scheduled", ai: true, tone: "neutral" },
  ] as const;
  return <Panel title="Alert Center" eyebrow={`${selectedSymbol} · webhook-ready`} action={<SampleBadge>Simulated</SampleBadge>}><div className="divide-y divide-border">{alerts.map((alert) => <div key={`${alert.time}-${alert.trigger}`} className="grid grid-cols-[auto_1fr_auto] gap-3 p-3"><span className={cn("mt-1.5 size-1.5 rounded-full", alert.tone === "positive" ? "bg-positive" : alert.tone === "warning" ? "bg-warning" : "bg-muted-foreground")} /><div className="min-w-0"><div className="flex flex-wrap items-center gap-2"><b className="text-[10px]">{selectedSymbol}</b><span className="text-[9px] text-muted-foreground">{alert.type}</span></div><p className="mt-1 text-[11px] font-medium">{alert.trigger}</p><p className="mt-1 text-[9px] text-muted-foreground">{alert.time} · {alert.status}</p></div><div className={cn("flex h-fit items-center gap-1 text-[8px] uppercase", alert.ai ? "text-primary" : "text-muted-foreground")}>{alert.ai ? <BrainCircuit className="size-3" /> : <Check className="size-3" />}{alert.ai ? "AI analysis available" : "Awaiting analysis"}</div></div>)}</div><div className="flex items-center gap-2 border-t border-border bg-secondary/30 px-3 py-2.5 text-[9px] text-muted-foreground"><Webhook className="size-3 text-primary" />Ready for future verified TradingView webhook events</div></Panel>;
}

export function Dashboard() {
  const { preferences } = useDashboard();
  return <div><MarketOverviewStrip /><div className="p-3 md:p-4"><div className="mb-3 flex flex-col gap-3 xl:flex-row xl:items-end xl:justify-between"><div><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">Workspace 01</p><h1 className="mt-1 text-xl font-semibold">Trading Dashboard</h1></div><div className="flex min-w-0 flex-1 flex-col gap-2 xl:max-w-2xl"><MarketRegimeIndicator /><div className="hidden items-center justify-end gap-2 text-[10px] text-muted-foreground sm:flex"><BellRing className="size-3" />Sample intelligence · prototype only</div></div></div><div className="grid min-w-0 gap-3 xl:grid-cols-[220px_minmax(0,1fr)_300px]"><div className="xl:col-start-1 xl:row-span-2 xl:row-start-1"><WatchlistPanel /></div><div className="xl:col-start-2 xl:row-start-1"><TradingViewChartPanel /></div>{preferences.visiblePanels.news && <div className="xl:col-start-3 xl:row-span-2 xl:row-start-1"><MarketNewsPanel /></div>}{preferences.visiblePanels.earnings && <div className="xl:col-start-2 xl:row-start-2"><EarningsMonitorPanel /></div>}{preferences.visiblePanels.alerts && <div className="xl:col-start-1 xl:row-start-3"><AlertsPanel /></div>}{preferences.visiblePanels.analyzer && <div className="xl:col-span-2 xl:col-start-2 xl:row-start-3"><AITradeAnalyzerPanel /></div>}<div className="xl:col-span-3"><OptionsContractLab /></div></div></div></div>;
}
