import { BookOpen, Check, FlaskConical, PlugZap, ShieldAlert } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { getCompany, glossary } from "./data";
import { useDashboard } from "./dashboard-context";
import { AITradeAnalyzerPanel, EarningsMonitorPanel, MarketNewsPanel, WatchlistPanel } from "./dashboard-panels";
import { Panel, SampleBadge, StatusDot } from "./ui";

export function PageHeader({ eyebrow, title, description }: { eyebrow: string; title: string; description: string }) { return <header className="mb-5 border-b border-border pb-5"><p className="text-[10px] font-semibold uppercase tracking-[0.18em] text-primary">{eyebrow}</p><h1 className="mt-2 text-2xl font-semibold">{title}</h1><p className="mt-2 max-w-2xl text-sm leading-relaxed text-muted-foreground">{description}</p></header>; }
export function WatchlistPage() { return <div className="mx-auto max-w-5xl p-4 md:p-6"><PageHeader eyebrow="Portfolio workspace" title="My Watchlist" description="Organize the companies you monitor. Changes are stored on this device for the prototype." /><WatchlistPanel management /></div>; }
export function NewsPage() { return <div className="mx-auto max-w-5xl p-4 md:p-6"><PageHeader eyebrow="Market intelligence" title="Company News" description="Review categorized sample headlines for the active ticker. A live news provider is not connected." /><MarketNewsPanel full /></div>; }
export function EarningsPage() { return <div className="mx-auto max-w-5xl p-4 md:p-6"><PageHeader eyebrow="Catalyst calendar" title="Earnings Monitor" description="Study upcoming sample earnings details and historical post-report reactions." /><EarningsMonitorPanel full /></div>; }
export function AnalyzerPage() { return <div className="mx-auto max-w-6xl p-4 md:p-6"><PageHeader eyebrow="Explainable analysis" title="AI Trade Analyzer" description="Review how a future engine will weigh technical conditions, catalysts, invalidation points, and risk without forcing a trade." /><AITradeAnalyzerPanel full /></div>; }
export function OptionsLabPage() { return <div className="grid min-h-[calc(100vh-3.5rem)] place-items-center p-6"><div className="max-w-lg text-center"><span className="mx-auto grid size-14 place-items-center border border-primary/30 bg-primary/10 text-primary"><FlaskConical /></span><SampleBadge>Coming soon</SampleBadge><h1 className="mt-5 text-2xl font-semibold">Options Lab</h1><p className="mt-3 text-sm leading-relaxed text-muted-foreground">A future workspace for options chains, strategy comparisons, implied volatility, and defined-risk scenario modeling.</p><Button className="mt-6" disabled>Join the waitlist</Button></div></div>; }
export function LearningPage() { return <div className="mx-auto max-w-5xl p-4 md:p-6"><PageHeader eyebrow="Beginner education" title="Learning Center" description="Plain-language foundations for understanding options, technical signals, and risk." /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{Object.entries(glossary).map(([term, definition]) => <article key={term} className="border border-border bg-card p-4"><BookOpen className="size-4 text-primary" /><h2 className="mt-4 text-sm font-semibold">{term}</h2><p className="mt-2 text-xs leading-relaxed text-muted-foreground">{definition}</p></article>)}</div><div className="mt-4 border border-warning/25 bg-warning/5 p-4 text-xs leading-relaxed text-muted-foreground"><ShieldAlert className="mr-2 inline size-4 text-warning" />Options are complex and involve risk. Education does not replace independent research or professional advice.</div></div>; }
export function SettingsPage() { const { watchlist, selectedSymbol, preferences, updatePreferences, togglePanel } = useDashboard(); const company = getCompany(selectedSymbol); return <div className="mx-auto max-w-5xl p-4 md:p-6"><PageHeader eyebrow="Workspace controls" title="Settings" description="Choose how the prototype behaves and which intelligence panels appear on your dashboard." /><div className="grid gap-4 lg:grid-cols-2"><Panel title="Dashboard layout" eyebrow="Visible panels"><div className="divide-y divide-border">{Object.entries(preferences.visiblePanels).map(([key, enabled]) => <SettingRow key={key} label={`${key.charAt(0).toUpperCase()}${key.slice(1)} panel`} description={enabled ? "Visible on dashboard" : "Hidden from dashboard"}><Toggle checked={enabled} label={`${key} panel`} onChange={() => togglePanel(key as keyof typeof preferences.visiblePanels)} /></SettingRow>)}</div></Panel><Panel title="Chart preferences" eyebrow={`Active ticker · ${company.symbol}`}><div className="p-4"><label className="text-xs font-medium" htmlFor="timeframe">Default timeframe</label><Select value={preferences.timeframe} onValueChange={(timeframe) => updatePreferences({ timeframe })}><SelectTrigger id="timeframe" className="mt-2"><SelectValue /></SelectTrigger><SelectContent>{["1D","5D","1M","3M","6M","1Y"].map((item) => <SelectItem key={item} value={item}>{item}</SelectItem>)}</SelectContent></Select><SettingRow label="Compact information density" description="Reduce vertical spacing in market panels"><Toggle checked={preferences.compactMode} label="Compact information density" onChange={() => updatePreferences({ compactMode: !preferences.compactMode })} /></SettingRow></div></Panel><Panel title="Notifications" eyebrow="Prototype preferences"><SettingRow label="Catalyst reminders" description="Prepare alerts for earnings and high-impact news"><Toggle checked={preferences.notifications} label="Catalyst reminders" onChange={() => updatePreferences({ notifications: !preferences.notifications })} /></SettingRow><SettingRow label="Watchlist capacity" description={`${watchlist.length} of 15 symbols`}><Check className="size-4 text-positive" /></SettingRow></Panel><Panel title="Data providers" eyebrow="Connection status"><div className="divide-y divide-border">{["Market data", "Company news", "Earnings", "AI analysis", "Options chain"].map((name) => <SettingRow key={name} label={name} description="Secure server connection not configured"><span className="flex items-center gap-2 text-[10px] uppercase text-muted-foreground"><StatusDot />Disconnected</span></SettingRow>)}</div><div className="border-t border-border bg-secondary/30 p-4 text-[10px] leading-relaxed text-muted-foreground"><PlugZap className="mr-2 inline size-3 text-primary" />API keys will be handled by secure server-side services, never exposed in the browser.</div></Panel></div></div>; }
function Toggle({ checked, label, onChange }: { checked: boolean; label: string; onChange: () => void }) { return <Button type="button" variant="ghost" size="icon" role="switch" aria-checked={checked} aria-label={label} onClick={onChange} className={`h-5 w-9 rounded-full border-2 p-0 ${checked ? "border-primary bg-primary hover:bg-primary/90" : "border-input bg-input hover:bg-input"}`}><span className={`block size-3.5 rounded-full bg-background transition-transform ${checked ? "translate-x-2" : "-translate-x-2"}`} /></Button>; }
function SettingRow({ label, description, children }: { label: string; description: string; children: React.ReactNode }) { return <div className="flex min-h-16 items-center justify-between gap-4 p-4"><div><p className="text-xs font-medium">{label}</p><p className="mt-1 text-[10px] text-muted-foreground">{description}</p></div>{children}</div>; }
